name: Tests

on: push

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    steps:
      # - name: Set environment variable
      #   uses: actions/set-env-variable@v2
      #   with:
      #     name: GITHUB_TOKEN
      #     value: 'TEST_TOKEN'
      #     public: true
      - name: Set environment variable 2
        run: |
          # echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          # curl https://httpbin.org/json >> $GITHUB_ENV
          # echo 'EOF' >> $GITHUB_ENV

          echo 'NEW_VARIABLE<<EOF' >> $GITHUB_ENV
          curl https://httpbin.org/json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Set environment variable 3
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        run: |
          echo "${{ env.action_state }}"
          echo "${{ env.JSON_RESPONSE }}"