name: Github secrets
author: "Douglas Francisco Cardoso <douglas.cardoso.nl@leiainc.com>"
description: "This can export every secrets from Github to environment variables"
 inputs:
   secrets:
     description: "Secrets list to get from AWS Secrets Manager"
     required: true
# outputs:
#   time:
#     description: "The current time"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secrets }}